### ISSUE TITLE
Bring back @import bootstrap/variables

### ISSUE THREAD

**Issue by rstacruz** [jasontorres/bootstrap-on-rails#18]
I see that the only difference from the official Bootstrap distribution is that variables.less is excluded:

https://github.com/jasontorres/bootstrap-on-rails/pull/16#discussion_r21345273

This is not necessary. You can change variables in this manner:

```css
@import "bootstrap/bootstrap";
@brand-danger: #f82ca0;
```

Less variables are not evaluated like programming languages, counter-intuitively... you can define a variable *after* its being used.

```css
p { color: @red; }
@red: #ff0000;

/* output: p { color: #ff0000 } */
```

Conversely, this allows you to override variables after rules are in place:

```css
@red: #ff0000;
p { color: @red; }
@red: #ee5533;

/* output: p { color: #ee5533 } */
```
